[package]
name = "bevy_nokhwa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["render"]
render = ["bevy/render", "bevy/bevy_asset", "bevy/bevy_winit", "bevy/x11"]


[dependencies]
bevy = { version = "0.9.1", default-features = false }
bytemuck = { version = "1.7.0" }
image = { version = "0.24", default-features = false, features = [] }
nokhwa = { version = "0.10.0", features = ["input-native", "output-wgpu"] }
